#include <stdio.h>
#include "esp_log.h"
#include "esp_err.h"
#include <string.h>
#include "esp_smartconfig.h"
#include <errno.h>

#include <string.h>
#include <sys/param.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_netif.h"
#include "lwip/err.h"
#include "lwip/sockets.h"
#include "lwip/sys.h"
#include <lwip/netdb.h>
#include "mqtt_client.h"
#include "freertos/semphr.h"
#include "esp_mac.h"
